### ISSUE TITLE
Error when trying example

### ISSUE THREAD

**Issue by lancioni** [sinaahmadi/klpt#11]
When trying one of the transliteration examples in the main project page,

transliterate = Transliterate("Kurmanji", "Latin", target_script="Arabic"
transliterate.transliterate("rojhilata navîn")

I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\klpt\transliterate.py", line 162, in transliterate
    tokens_dict = self.to_pieces(token)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\klpt\transliterate.py", line 131, in to_pieces
    tokens_dict[char_index-i] = tokens_dict[char_index-i] + token[char_index]
KeyError: 1

I am using Python 3.6.3 under Windows 10.

Thanks for support!

Giuliano

**Comment by sinaahmadi** [comment]
Thanks for raising the issue, Giuliano.

It is weird, as I cannot reproduce the same bug with your code.
Would you please try the following code or provide your entire code here?

```
>>> from klpt.transliterate import Transliterate
>>> transliterate = Transliterate("Kurmanji", "Latin", target_script="Arabic")
>>> transliterate.transliterate("rojhilata navîn")
'رۆژهلاتا ناڤین'
```

**Comment by lancioni** [comment]
Strangely enough, it gave the error by writing exactly what you wrote:

![immagine](https://user-images.githubusercontent.com/3199462/120079845-18590480-c0b6-11eb-9aae-7ed65b629647.png)

**Comment by lancioni** [comment]
On the other hand, it works in Linux Subsystem for Windows:

![immagine](https://user-images.githubusercontent.com/3199462/120079915-75ed5100-c0b6-11eb-97e6-772ce82a2ec2.png)

So, it seems to be a Windows issue, although the library was installed through pip with no complain. Strange!

**Comment by sinaahmadi** [comment]
This is really weird. I, unluckily, have not tested the library on Windows yet.
Thanks so much again for reporting it. I'll find a way to test it on Windows soon.
