### ISSUE TITLE
morphology for kurmanji

### ISSUE THREAD

**Issue by ftyers** [sinaahmadi/klpt#3]
The apertium project has a morphological analyser for Kurmanji:
https://github.com/apertium/apertium-kmr

You could include it to get morphological analysis for Kurmanji. :)

It recognises 342870 forms and you can get a full form list using the `lt-expand` tool:

```
$ lt-expand apertium-kmr.kmr.dix  | wc -l
342870
```

**Comment by sinaahmadi** [comment]
Thanks, Francis. I was aware of it and will definitely include it. 
Thanks for your kind attention 😊

**Comment by ftyers** [comment]
If you would like help using the Apertium tools, please feel free to get in contact with us, either here or on IRC or on our mailing list. We know that our documentation isn't the best in the world!

I'm also happy to do some data conversion if it's more convenient for you.

**Comment by sinaahmadi** [comment]
So, my initial idea was to update the current [Hunspell system of Kurmanji](https://cgit.freedesktop.org/libreoffice/dictionaries/tree/kmr_Latn/kmr_Latn.aff) which is outdated. A while ago, I was asked by the Open Office community to update it. 

I think the best idea would be to convert the Apertium data into a Hunspell Affix file; *une pierre, deux coups*! Otherwise, using a wrapper should do the job to directly integrate Apertium in KLPT.

**Comment by ftyers** [comment]
Hmm, I think either of those methods could work. If I remember correctly @flammie has some code for this. There is an [apertium-python](https://github.com/apertium/apertium-python) package, but it's very alpha, and you might be better just writing a parser for the output of `lt-expand`.

**Comment by ftyers** [comment]
Another thing that could be done is just add support for `ATT` format files, which are transducers in the following format: 
```
$ lt-print kmr.automorf.bin  | head
0	1	y	y	0.000000	
0	2	ê	ê	0.000000	
0	2	e	ê	0.000000	
0	3	b	b	0.000000	
0	4	d	d	0.000000	
```

**Comment by ftyers** [comment]
I made a basic PR in #5, this code is kind of pedagogical so it isn't super optimised. Måns Huldén has some code for processing ATT files too, you can find it [here](https://github.com/mhulden/foma/blob/master/foma/python/attapply.py).

**Comment by sinaahmadi** [comment]
Yeah 😁 Automata are really fun!

Thank you very much again, Francis. This was so quick and efficient. Your contribution should be available in the next release and can be used the exact same way as Sorani:

```
from klpt.stem import Stem
morph_analyzer = Stem("Kurmanji", "Latin")
print(morph_analyzer.analyze("bibêje"))
[{'base': 'gotin', 'description': 'vblex_tv_prs_p3_sg', 'pos': '', 'terminal_suffix': '', 'formation': ''}, {'base': 'gotin', 'description': 'vblex_tv_imp_p2_sg', 'pos': '', 'terminal_suffix': '', 'formation': ''}, {'base': 'gotin', 'description': 'vblex_tv_fut_p3_sg', 'pos': '', 'terminal_suffix': '', 'formation': ''}]
```

There are some delicate details that I'll take care of later, particularly structuring the output of theATT analyzer.
[Here](https://github.com/sinaahmadi/klpt/blob/7a9653ab2aea4b4657387d0e81a6a3979d8628ee/klpt/stem.py#L166) you can see how it is integrated in the `stem` module.

You should also appear in the contributors section in the README soon ;-)
