### ISSUE TITLE
Some words aren't analysed, although they are in Apertium

### ISSUE THREAD

**Issue by ftyers** [sinaahmadi/klpt#6]
Output of Python analyser:
```
('dixwî', [[]])
```
Output of Apertium:
```bash
$ echo dixwî | apertium -d ~/source/apertium/languages/apertium-kmr/ kmr-morph
^dixwî/xwarin<vblex><tv><pri><p2><sg>$
```
I will look into this. Feel free to assign it to me.

**Comment by sinaahmadi** [comment]
Just noticed it, Francis. 
Sure. I assigned it to you. Please consider adding such cases to [test_stem.py](https://github.com/sinaahmadi/klpt/blob/master/tests/test_stem.py). 
Thanks!

**Comment by ftyers** [comment]
It seems to be to do with sequences of epsilons:
```bash
fran@ipek:~/source/klpt$ hfst-txt2fst klpt/data/kmr-analyser.att | hfst-fst2strings -e '0' | grep "d0*i0*x0*w0*î"
dixw00000î00:xwarin<vblex><tv><pri><p2><sg>0
```

**Comment by sinaahmadi** [comment]
I see.
Do you think it has something to do with [`att_analyzer.py`](https://github.com/sinaahmadi/klpt/blob/master/klpt/att_analyze.py)? We can try with [this one](https://github.com/mhulden/foma/blob/master/foma/python/attapply.py) as you suggested before.

**Comment by ftyers** [comment]
Yep, it's definitely in there, I'll try and play around a bit more and if I can't get it to work we can try the one that Måns wrote :)
